# Base image
FROM node:20-alpine

# Set working directory
WORKDIR /usr/src/app

# Install all dependencies including devDependencies
COPY package*.json ./
RUN npm install

# Copy app code
COPY . .

# Expose port for dev
ENV NODE_ENV=development
ENV PORT=8002
EXPOSE 8002

# Optional: install nodemon globally for live-reload
RUN npm install -g nodemon

# Use nodemon for hot reload in development
CMD ["nodemon", "src/server.js"]
